# Generated by Django 6.0.7 on 2026-07-24 14:59

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('level', models.CharField(choices=[('COUNTY', 'County'), ('SUB_COUNTY', 'Sub-County'), ('WARD', 'Ward')], default='SUB_COUNTY', max_length=20)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name': 'Administrative Region',
                'verbose_name_plural': 'Administrative Regions',
                'indexes': [models.Index(fields=['code', 'level'], name='base_admini_code_de535a_idx')],
            },
        ),
        migrations.CreateModel(
            name='HealthWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('role', models.CharField(choices=[('CHP', 'Community Health Promoter'), ('EPI', 'Sub-County Epidemiologist'), ('FACILITY_LEAD', 'Health Facility In-Charge'), ('NGO_COORD', 'Vector Control / NGO Coordinator')], default='CHP', max_length=30)),
                ('preferred_channel', models.CharField(choices=[('SMS', 'SMS Text Message'), ('WHATSAPP', 'WhatsApp Message'), ('EMAIL', 'Email Notification')], default='SMS', max_length=10)),
                ('assigned_facility', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_regions', models.ManyToManyField(blank=True, related_name='health_workers', to='base.administrativeregion')),
            ],
            options={
                'verbose_name': 'Health Worker',
                'verbose_name_plural': 'Health Worker Registry',
            },
        ),
        migrations.CreateModel(
            name='SpatialGridCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_id', models.IntegerField(db_index=True, unique=True)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('centroid', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('district_name', models.CharField(db_index=True, max_length=100)),
                ('has_population', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Spatial Grid Cell',
                'verbose_name_plural': 'Spatial Grid Cells',
                'indexes': [models.Index(fields=['cell_id'], name='base_spatia_cell_id_2b1e24_idx'), models.Index(fields=['district_name'], name='base_spatia_distric_5ca1d3_idx')],
            },
        ),
        migrations.CreateModel(
            name='AlertDispatchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.FloatField()),
                ('message_body', models.TextField()),
                ('channel_used', models.CharField(max_length=10)),
                ('dispatch_status', models.CharField(choices=[('PENDING', 'Pending'), ('DISPATCHED', 'Dispatched'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('provider_sid', models.CharField(blank=True, max_length=100, null=True)),
                ('dispatched_at', models.DateTimeField(auto_now_add=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_logs', to='base.healthworker')),
                ('grid_cell', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.spatialgridcell')),
            ],
            options={
                'verbose_name': 'Alert Dispatch Log',
                'verbose_name_plural': 'Alert Dispatch Logs',
                'ordering': ['-dispatched_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskAssessmentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_step', models.DateField(db_index=True)),
                ('hazard_score', models.FloatField()),
                ('exposure_score', models.FloatField()),
                ('vulnerability_score', models.FloatField()),
                ('raw_tri', models.FloatField()),
                ('healthcare_deficit_index', models.FloatField(default=0.0)),
                ('surveillance_multiplier', models.FloatField(default=1.0)),
                ('primary_risk_score', models.FloatField()),
                ('secondary_risk_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessments', to='base.spatialgridcell')),
            ],
            options={
                'verbose_name': 'Risk Assessment Run',
                'verbose_name_plural': 'Risk Assessment Runs',
                'indexes': [models.Index(fields=['time_step', 'secondary_risk_score'], name='base_riskas_time_st_0ef4e0_idx'), models.Index(fields=['time_step', 'primary_risk_score'], name='base_riskas_time_st_256754_idx')],
                'unique_together': {('cell', 'time_step')},
            },
        ),
        migrations.CreateModel(
            name='RawGridFeatureStaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_step', models.DateField(db_index=True)),
                ('lst_day_celsius', models.FloatField(blank=True, null=True)),
                ('lst_night_celsius', models.FloatField(blank=True, null=True)),
                ('precip_mm', models.FloatField(blank=True, null=True)),
                ('ndvi_val', models.FloatField(blank=True, null=True)),
                ('vertisol_percent', models.FloatField(blank=True, null=True)),
                ('elevation_m', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staged_features', to='base.spatialgridcell')),
            ],
            options={
                'verbose_name': 'Raw Grid Feature Staging',
                'verbose_name_plural': 'Raw Grid Feature Staging Records',
                'indexes': [models.Index(fields=['time_step', 'cell'], name='base_rawgri_time_st_fe5839_idx')],
                'unique_together': {('cell', 'time_step')},
            },
        ),
    ]
