# Generated by Django 5.2.16 on 2026-07-25 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_spatialgridcell_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='spatialgridcell',
            name='health_travel_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='spatialgridcell',
            name='healthcare_deficit',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='spatialgridcell',
            name='malnutrition_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='spatialgridcell',
            name='pop_density',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='spatialgridcell',
            name='poverty_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='spatialgridcell',
            name='settlement_dist',
            field=models.FloatField(default=0.0),
        ),
    ]
